@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWNhYTJlMWZjZWI2N2VkMGRmYTI2NTYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzQ4ODc4MDIsImV4cCI6MTc3NDg4ODcwMn0.Rnp9z8F3MUK5_mbzQN4WZ75ZVkemYJp_jMaLIwbIe-g
@refreshToken = 9b8765965e23bdd0972f8d05aef240c1cbb4c8df68261f81b67dcf19fa9bb3d1dd4ed444bf5d8c160fcdfcaebf6f9f784c02db18de4a15582d964686f4455783


### 1. Registrar un usuario válido
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "12345678"
}

###

### 2. Validar email 
PUT http://localhost:3000/api/user/validation
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "verificationCode": "589269"
}

###

### 3. Login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "12345678"
}

###

### 4. Onboarding Usuario
PUT http://localhost:3000/api/user/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test",
  "lastName": "Usuario",
  "nif": "12345678A"
}

###

### 5. Onboarding Compañia
PATCH http://localhost:3000/api/user/company
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "compañia1",
  "cif": "A-12344978",
  "address": {
    "street":"x",
    "number": 1,
    "postal": "00000",
    "city": "x",
    "province": "x"
  },
  "isFreelance": false
}

###

### 6. Subir logo
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="logo"; filename="logo.png"
Content-Type: image/png

< ./logo.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

### 7. Obtener Usuario
GET http://localhost:3000/api/user
Authorization: Bearer {{token}}

### 

### 8. Refresh Token
POST http://localhost:3000/api/user/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###

### 9. Logout
POST http://localhost:3000/api/user/logout
Authorization: Bearer {{token}}

###

### 10. Hard Delete
DELETE http://localhost:3000/api/user
Authorization: Bearer {{token}}

###

### 11. Soft Delete
DELETE http://localhost:3000/api/user?soft=true
Authorization: Bearer {{token}}

###

### 12. Cambia Contrasela
PUT http://localhost:3000/api/user/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "JAJAJAJJAJAJAJAJ",
  "newPassword": "12345678"
}