@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWM5NTllN2Y3YjM2ZGRhNWM0ZWU2YTgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzQ4MTQ3MzYsImV4cCI6MTc3NDgxNTYzNn0.u5ENcKoZwrkErbqI1e6QTJQFKwtpH4dWT2dnzQ9T9ic

@refreshToken = 7992ea3fba6db5558a8630b87783ad87c0f9a4a0f71b4477b06e846c1c63debd59788a0b2acd2a2397943e5915e036a99f77a230c741feda4fc44d929f7e16a2

### 1. Registrar un usuario válido
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "freelance@mail.com",
  "password": "12345678"
}

###

### 2. Validar email 

PUT http://localhost:3000/api/user/validation
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "verificationCode": "000000"
}

###

### 3. Login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "12345678"
}

###

### 4. Onboarding Usuario

PUT http://localhost:3000/api/user/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test",
  "lastName": "Usuario",
  "nif": "12345678A"
}

###

### 5. Onboarding Compañia
PATCH http://localhost:3000/api/user/company
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "compañia1",
  "cif": "A-12344978",
  "address": {
    "street":"x",
    "number": 1,
    "postal": "00000",
    "city": "x",
    "province": "x"
  },
  "isFreelance": true
}

###

### 6. Subir logo
curl -X PATCH http://localhost:3000/api/user/logo \
  -H "Authorization: Bearer {{token}}" \
  -F "logo=@./logo.png"

###

### 7. Obtener todos los usuarios
GET http://localhost:3000/api/user
Authorization: Bearer {{token}}

### 

### 8. Refresh Token
POST http://localhost:3000/api/user/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###

### 9. Logout
POST http://localhost:3000/api/user/logout
Authorization: Bearer {{token}}