@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWM5NTllN2Y3YjM2ZGRhNWM0ZWU2YTgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzQ4MDY0NTksImV4cCI6MTc3NDgwNzM1OX0.lZm6BCHulqb7Lrvgazx54OgdVTheO5z7X0qbo8JyZ50

### 1. Registrar un usuario válido
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "freelance@mail.com",
  "password": "12345678"
}

###

### 2. Validar email 

PUT http://localhost:3000/api/user/validation
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "verificationCode": "000000"
}

###

### 3. Login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "12345678"
}

###

### 4. Onboarding Usuario

PUT http://localhost:3000/api/user/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test",
  "lastName": "Usuario",
  "nif": "12345678A"
}

###

### 5. Onboarding Compañia
PATCH http://localhost:3000/api/user/company
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "compañia1",
  "cif": "A-12344978",
  "address": {
    "street":"x",
    "number": 1,
    "postal": "00000",
    "city": "x",
    "province": "x"
  },
  "isFreelance": true
}

###

### 7. Obtener todos los usuarios
GET http://localhost:3000/api/user
Authorization: Bearer {{token}}

